convert toMapData functions to DTO's and delete unused models
gridsuite/network-map-server pull request #134
Opened 2023-08-23 09:49 UTC by achour94

2023-08-25 09:54 UTC, FranckLecuyer requested changes
There are still toMapData methods for the ratioTapChanger, phaseTapChanger, current limits for the two windings transformers and lines ...

2023-08-25 09:54 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/network/map/model/ElementType.java
> +    VOLTAGE_LEVEL_EQUIPMENTS(Connectable.class, AbstractVoltageLevelEquipmentsInfos::toData),
VOLTAGE_LEVELS_CONNECTABLES or CONNECTABLES ?

2023-09-08 09:55 UTC, AAJELLAL commented on src/main/java/org/gridsuite/network/map/dto/bus/AbstractBusInfos.java
> +package org.gridsuite.network.map.dto.bus;
You need to add copyright:
/**
 * Copyright (c) 2023, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

2023-09-08 09:55 UTC, AAJELLAL commented on src/main/java/org/gridsuite/network/map/dto/bus/BusListInfos.java
> +package org.gridsuite.network.map.dto.bus;
The same thing here

2023-09-08 09:55 UTC, AAJELLAL commented on src/main/java/org/gridsuite/network/map/dto/voltagelevelequipments/AbstractVoltageLevelEquipmentsInfos.java
> +package org.gridsuite.network.map.dto.voltagelevelequipments;
Copyright

2023-09-08 09:55 UTC, AAJELLAL commented on src/main/java/org/gridsuite/network/map/dto/voltagelevelequipments/VoltageLevelEquipmentsListInfos.java
> +package org.gridsuite.network.map.dto.voltagelevelequipments;
Copyright

2023-11-14 14:32 UTC, closed without merging