Add terminal connection state for battery in tab view
gridsuite/network-map-server pull request #140
Opened 2023-09-21 08:44 UTC by FranckLecuyer

2023-09-21 15:07 UTC, dbraquart requested changes
code: ok, but revert HvdcTabInfos.java
tests: ok

2023-09-21 15:07 UTC, dbraquart commented on src/main/java/org/gridsuite/network/map/dto/definition/hvdc/HvdcTabInfos.java
> -
you should revert this file

2023-09-21 15:41 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/network/map/dto/definition/hvdc/HvdcTabInfos.java
> -
Done

2023-09-21 16:02 UTC, dbraquart approved these changes
code: ok
tests: ok

2023-09-22 11:24 UTC, antoinebhs approved these changes
Code OK
Tests OK

2023-09-22 11:48 UTC, merged