feat(properties): generalize the use and them on loads
gridsuite/network-map-server pull request #154
Opened 2024-01-12 11:03 UTC by TheMaskedTurtle

2024-01-17 15:33 UTC, dbraquart requested changes
code: ok, but 1 header missing
tests: no back-end issue

2024-01-18 09:59 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/network/map/dto/ElementFormInfosWithProperties.java
> +package org.gridsuite.network.map.dto;
Done

2024-01-18 10:03 UTC, Mathieu-Deharbe approved these changes

2024-01-18 10:03 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/network/map/dto/ElementFormInfosWithProperties.java
> +package org.gridsuite.network.map.dto;
We are in 2024!

2024-01-18 10:26 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/network/map/dto/ElementFormInfosWithProperties.java
> +package org.gridsuite.network.map.dto;
I forget about it already ! Fixed

2024-01-18 10:29 UTC, TheMaskedTurtle commented
> By the way I know this is way too late for this but I don't like the fact that those are just called "properties". That is very imprecise, everything belonging to the load is a property, like p0, q0... I liked the freeProperty denomination that I saw somewhere, because the user can freely add whatever he wants.

Hummm that is not really way too late actually ! We won't change the fact that in PowSyBl it's called properties as opposed to attributes (like p0, q0, etc) but I can still change it here though. Now it's factorized here and in the front so there are not so many places to update it, if you think it's worth it.

2024-01-18 10:43 UTC, Mathieu-Deharbe commented
> Hummm that is not really way too late actually ! We won't change the fact that in PowSyBl it's called properties as opposed to attributes (like p0, q0, etc) but I can still change it here though. Now it's factorized here and in the front so there are not so many places to update it, if you think it's worth it.

No I don't think this is worth it. It is better to follow powsybl naming. And it is already quite good that "attributes" and "properties" are differentiated. Thanks for the clarification.

2024-01-22 12:25 UTC, dbraquart approved these changes

2024-01-22 15:38 UTC, merged