Add busbar section tab infos
gridsuite/network-map-server pull request #160
Opened 2024-02-15 15:54 UTC by Meklo

Signed-off-by: Hugo Marcellin <hugo.marcelin@rte-france.com>

2024-02-16 13:03 UTC, FranckLecuyer requested changes
You considered only the buses from the network BusbarSection objects,
so it is only available for voltage level in NODE_BREAKER topology ...

We should consider all network buses objects

2024-02-19 16:18 UTC, dbraquart approved these changes
code: ok
tests: ok

2024-02-20 11:00 UTC, FranckLecuyer requested changes

2024-02-20 12:09 UTC, FranckLecuyer approved these changes

2024-02-20 12:57 UTC, Meklo commented on src/main/java/org/gridsuite/network/map/NetworkMapService.java
> +                .distinct();
Not really sure but it's done for all other types of equipments so i've added it for homogeneity's sake

2024-02-20 15:31 UTC, merged