Fetch substation ID for voltage level
gridsuite/network-map-server pull request #213
Opened 2024-10-23 13:43 UTC by souissimai

2024-11-07 16:45 UTC, SlimaneAmar requested changes

2024-11-07 16:45 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/network/map/NetworkMapService.java
> +        return network.getVoltageLevel(voltageLevelId).getNullableSubstation().getId();
```suggestion
          return network.getVoltageLevel(voltageLevelId).getSubstation().map(Substation::getId).orElse(null))
```

2024-11-08 15:08 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/network/map/NetworkMapService.java
> +        return network.getVoltageLevel(voltageLevelId).getSubstation().map(Substation::getId).orElse(null);
Add a test for null

2024-11-12 09:36 UTC, souissimai commented on src/main/java/org/gridsuite/network/map/NetworkMapService.java
> +        return network.getVoltageLevel(voltageLevelId).getSubstation().map(Substation::getId).orElse(null);
done

2024-11-12 15:43 UTC, SlimaneAmar approved these changes

2024-11-13 12:10 UTC, merged