adds all the limit set data to LineFormInfos
gridsuite/network-map-server pull request #226
Opened 2024-11-21 14:43 UTC by Mathieu-Deharbe

2025-01-03 08:09 UTC, basseche commented on src/test/resources/line-form-data.json
> +      "id" : "limit set 1",
limit set 2 ?

2025-01-03 08:09 UTC, basseche commented on src/test/resources/line-form-data.json
> +  "selectedOperationalLimitsGroupId2": "limit set 1",
limit set 2 ?

2025-01-03 15:58 UTC, ghazwarhili requested changes

2025-01-03 15:58 UTC, ghazwarhili commented on src/main/java/org/gridsuite/network/map/dto/mapper/LineInfosMapper.java
> +        }
```       
 Map<Collection<OperationalLimitsGroup>, Consumer<List<CurrentLimitsData>>> limitsMap = Map.of(
                line.getOperationalLimitsGroups1(), builder::currentLimits1,
                line.getOperationalLimitsGroups2(), builder::currentLimits2
        );

        limitsMap.forEach((groups, setter) -> {
            List<CurrentLimitsData> limitsData = groups.stream()
                    .map(ElementUtils::operationalLimitsGroupToMapDataCurrentLimits)
                    .toList();
            if (!limitsData.isEmpty()) {
                setter.accept(limitsData);
            }
        });
        }
```

We can even do better by extracting this code into a utility function to avoid code duplication with the one from twoWT

```
setOperationalLimitsData(builder, twoWT.getOperationalLimitsGroups1(), builder::currentLimits1);
        setOperationalLimitsData(builder, twoWT.getOperationalLimitsGroups2(), builder::currentLimits2);
        }
```

2025-01-03 15:58 UTC, ghazwarhili commented on src/main/java/org/gridsuite/network/map/dto/mapper/TwoWindingsTransformerInfosMapper.java
> +            builder.currentLimits2(currentLimits2Data);
The same remark as the one above

2025-01-03 15:58 UTC, ghazwarhili commented on src/main/java/org/gridsuite/network/map/dto/utils/ElementUtils.java
> +            CurrentLimits currentLimits = operationalLimitsGroup.getCurrentLimits().get();
Call "Optional#isPresent()" or "!Optional#isEmpty()" before accessing the value.

2025-01-03 15:58 UTC, ghazwarhili commented on src/main/java/org/gridsuite/network/map/dto/utils/ElementUtils.java
> +    public static CurrentLimitsData operationalLimitsGroupToMapDataCurrentLimits(OperationalLimitsGroup operationalLimitsGroup) {
we can add values check at the start of the function 
```
    if (operationalLimitsGroup == null || operationalLimitsGroup.getCurrentLimits().isEmpty()) {
        return null;
    }
```

2025-01-03 15:58 UTC, ghazwarhili commented on src/main/java/org/gridsuite/network/map/dto/utils/ElementUtils.java
> +        boolean empty = true;
boolean hasData = false (or something else)

provide a meaningful name for the variable

2025-01-03 15:58 UTC, ghazwarhili commented on src/main/java/org/gridsuite/network/map/dto/definition/line/LineFormInfos.java
> +    @JsonInclude(JsonInclude.Include.NON_EMPTY)
it not could be null ?
why NON_EMPTY ?

2025-01-06 15:05 UTC, Mathieu-Deharbe commented on src/test/resources/line-form-data.json
> +      "id" : "limit set 1",
Most of the time both sides use the same limit group name so I did it on purpose.

2025-01-06 15:05 UTC, Mathieu-Deharbe commented on src/test/resources/line-form-data.json
> +  "selectedOperationalLimitsGroupId2": "limit set 1",
Most of the time both sides use the same limit group name so I did it on purpose.

2025-01-06 15:24 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/network/map/dto/utils/ElementUtils.java
> +            CurrentLimits currentLimits = operationalLimitsGroup.getCurrentLimits().get();
Isn't it what I am doing in the previous line ?

2025-01-06 16:50 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/network/map/dto/mapper/LineInfosMapper.java
> +        }
I tried to do something like what you proposed but I separated both current limits. Let me know what you think (but I didn't test yet).

2025-01-06 16:50 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/network/map/dto/mapper/TwoWindingsTransformerInfosMapper.java
> +            builder.currentLimits2(currentLimits2Data);
And I did the same, the code is now common.

2025-01-29 13:15 UTC, basseche approved these changes

2025-02-05 08:17 UTC, ghazwarhili approved these changes

2025-02-10 14:13 UTC, merged