add tapChanger limits to transformers
gridsuite/network-map-server pull request #37
Opened 2021-06-17 14:53 UTC by JacquesBorsenberger

and minP maxP to generator data

2021-06-21 07:39 UTC, niconoir requested changes

2021-06-21 07:39 UTC, niconoir commented on src/main/java/org/gridsuite/network/map/model/TapChangerData.java
> + * Copyright (c) 2020, RTE (http://www.rte-france.com)
2021

2021-06-21 07:39 UTC, niconoir commented on src/main/java/org/gridsuite/network/map/NetworkMapService.java
> +    private static TapChangerData toMapData(TapChanger<?, ?> phaseTapChanger) {
Rename parameter phaseTapChanger to tapChanger (because it can be a ratio tap changer or a phase tap changer)

2021-06-21 13:56 UTC, niconoir approved these changes

2021-07-12 14:32 UTC, jonenst approved these changes

2021-07-12 14:36 UTC, merged