add information about HVDC lines
gridsuite/network-map-server pull request #59
Opened 2022-05-24 12:51 UTC by YenguiSeddik

2022-05-25 14:44 UTC, niconoir approved these changes

2022-05-31 10:50 UTC, FranckLecuyer requested changes

2022-05-31 10:50 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/network/map/model/HvdcLineMapData.java
> +    private float k;
Float with or without @JsonInclude annotation, like in other MapData dto ?

2022-05-31 10:50 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/network/map/NetworkMapControllerTest.java
> +        hvdcLine.addExtension(HvdcAngleDroopActivePowerControl.class, hvdcAngleDroopActivePowerControl);
Maybe keep also the test without the extensions, and check that in that case, nothing is generated for the extensions in json files ...

2022-06-02 08:07 UTC, FranckLecuyer approved these changes

2022-06-02 09:41 UTC, merged