Add values to transformers
gridsuite/network-map-server pull request #60
Opened 2022-05-27 10:04 UTC by bendaamerahm

- Add fields under Two Windings Transformers model
- Add fields under Three Windings Transformers model
- Add mapping
- update json tests files

2022-05-30 07:27 UTC, JacquesBorsenberger approved these changes

2022-05-30 12:52 UTC, sBouzols requested changes

2022-05-30 12:52 UTC, sBouzols commented on src/main/java/org/gridsuite/network/map/NetworkMapService.java
> +        if (!Double.isNaN(terminal1.getP())) {
This is already done line 147

2022-05-31 15:17 UTC, sBouzols approved these changes

2022-05-31 15:31 UTC, merged