add method to get voltage levels and their equipments
gridsuite/network-map-server pull request #65
Opened 2022-08-26 06:05 UTC by YenguiSeddik

2022-09-05 12:26 UTC, FranckLecuyer requested changes

2022-09-05 12:26 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/network/map/VoltageLevelsEquipmentsMapDataTest.java
> +package org.gridsuite.network.map;
Missing license and author

2022-09-05 12:26 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/network/map/VoltageLevelConnectableMapDataTest.java
> +package org.gridsuite.network.map;
Missing license and author

2022-09-05 12:26 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/network/map/model/VoltageLevelsEquipmentsMapData.java
> +package org.gridsuite.network.map.model;
Missing license and author

2022-09-05 12:26 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/network/map/model/VoltageLevelConnectableMapData.java
> +package org.gridsuite.network.map.model;
Missing license and author

2022-09-06 08:57 UTC, FranckLecuyer approved these changes

2022-09-06 10:20 UTC, laurgarn approved these changes

2022-09-06 10:20 UTC, laurgarn commented on src/main/java/org/gridsuite/network/map/NetworkMapService.java
> +        List<VoltageLevel> voltageLevels =  substationsId == null ?
You could have kept the "Stream style" all the way, as in `getVoltageLevels` above
```
    public List<VoltageLevelsEquipmentsMapData> getVoltageLevelsAndConnectable(UUID networkUuid, String variantId, List<String> substationsId) {
        Network network = getNetwork(networkUuid,
            substationsId == null ? PreloadingStrategy.COLLECTION : PreloadingStrategy.NONE,
            variantId);
        Stream<VoltageLevel> voltageLevels = substationsId == null ?
            network.getVoltageLevelStream() :
            substationsId.stream().flatMap(id -> network.getSubstation(id).getVoltageLevelStream());

        return voltageLevels.map(vl -> VoltageLevelsEquipmentsMapData.builder()
                .voltageLevel(toMapData(vl))
                .equipments(vl.getConnectableStream().map(NetworkMapService::toMapData).collect(Collectors.toList()))
                .build())
            .collect(Collectors.toList());
    }
```

2022-09-09 15:08 UTC, merged